# Generated by Django 5.2 on 2025-04-22 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('numleitos', models.IntegerField()),
                ('andar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('codconv', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('crm', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('especialidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('idade', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ambulatorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ambulatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('ambulatorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ambulatorio')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('porcent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.convenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Atende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
            options={
                'unique_together': {('medico', 'convenio')},
            },
        ),
        migrations.CreateModel(
            name='Possui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('vencimento', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.convenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'convenio')},
            },
        ),
    ]
