# Generated by Django 5.2 on 2025-04-22 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='ambulatorio',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='ambulatorio',
        ),
        migrations.AlterUniqueTogether(
            name='atende',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='atende',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='atende',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='possui',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='possui',
            name='paciente',
        ),
        migrations.AlterUniqueTogether(
            name='possui',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Ambulatorio',
        ),
        migrations.DeleteModel(
            name='Atende',
        ),
        migrations.DeleteModel(
            name='Medico',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='Convenio',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
        migrations.DeleteModel(
            name='Possui',
        ),
    ]
