# Generated by Django 5.2 on 2025-04-22 20:21

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_remove_paciente_ambulatorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreAmbulatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numleitos', models.IntegerField()),
                ('andar', models.IntegerField()),
            ],
            options={
                'db_table': 'core_ambulatorio',
            },
        ),
        migrations.CreateModel(
            name='CoreAuthGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'db_table': 'core_auth_group',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoreAuthPermission',
            fields=[
                ('permission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.permission')),
            ],
            options={
                'db_table': 'core_auth_permission',
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoreAuthUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_auth_user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CoreConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codconv', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_convenio',
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_django_content_type',
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'core_django_migrations',
            },
        ),
        migrations.CreateModel(
            name='CoreAuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthgroup')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthpermission')),
            ],
            options={
                'db_table': 'core_auth_group_permissions',
            },
        ),
        migrations.CreateModel(
            name='CoreAuthUserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthuser')),
            ],
            options={
                'db_table': 'core_auth_user_groups',
            },
        ),
        migrations.CreateModel(
            name='CoreAuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthpermission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthuser')),
            ],
            options={
                'db_table': 'core_auth_user_user_permissions',
            },
        ),
        migrations.CreateModel(
            name='CoreMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ambulatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreambulatorio')),
            ],
            options={
                'db_table': 'core_medico',
            },
        ),
        migrations.CreateModel(
            name='CoreAtende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreconvenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coremedico')),
            ],
            options={
                'db_table': 'core_atende',
            },
        ),
        migrations.CreateModel(
            name='CorePaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('ambulatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreambulatorio')),
            ],
            options={
                'db_table': 'core_paciente',
            },
        ),
        migrations.CreateModel(
            name='CoreConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('porcent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreconvenio')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coremedico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corepaciente')),
            ],
            options={
                'db_table': 'core_consulta',
            },
        ),
        migrations.CreateModel(
            name='CorePossui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=1)),
                ('vencimento', models.DateField()),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreconvenio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.corepaciente')),
            ],
            options={
                'db_table': 'core_possui',
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField()),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.coreauthuser')),
            ],
            options={
                'db_table': 'core_django_admin_log',
            },
        ),
    ]
